# Generated by Django 4.1.7 on 2023-03-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issue_tracker", "0004_remove_issue_type_old_issue_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateField(verbose_name="Дата начала")),
                (
                    "finished_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=3000, null=True, verbose_name="Описание"
                    ),
                ),
            ],
        ),
    ]
