# Generated by Django 4.1.7 on 2023-03-10 05:34
import django
from django.db import migrations, models


def add_project(apps, schema_editor):
    Issue = apps.get_model("issue_tracker", "Issue")
    for issue in Issue.objects.all():
        issue.project_id = 1
        issue.save()


class Migration(migrations.Migration):
    dependencies = [
        ("issue_tracker", "0005_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="issue_tracker.project",
            ),
        ),
        migrations.RunPython(add_project),
        migrations.AlterField(
            model_name="issue",
            name="project",
            field=models.ForeignKey(
                null=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="issue_tracker.project",
            ),
            preserve_default=False
        ),
    ]
