# Generated by Django 4.1.7 on 2023-03-10 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("issue_tracker", "0006_auto_20230310_0534"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="deleted_at",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="Дата и время удаления"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Удалено"),
        ),
        migrations.AlterField(
            model_name="issue",
            name="project",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Проект",
                to="issue_tracker.project",
            ),
        ),
    ]
