# Generated by Django 4.1.7 on 2023-03-20 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("issue_tracker", "0007_project_deleted_at_project_is_deleted_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_projects",
                        to="issue_tracker.project",
                        verbose_name="Проекты пользователя",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Проекты пользователя",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект пользователя",
                "verbose_name_plural": "Проекты пользователя",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="users",
            field=models.ManyToManyField(
                related_name="users_projects",
                through="issue_tracker.UserProjects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
