# Generated by Django 4.2 on 2023-04-17 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("issue_tracker", "0008_userprojects_project_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="project",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="issue_tracker.project",
            ),
        ),
    ]
